name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.7"
          cache: true

      - name: Extract version
        id: vars
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          mkdir -p dist
          for arch in amd64 arm64; do
            GOOS=linux GOARCH=$arch CGO_ENABLED=0 \
              go build -v -trimpath \
              -ldflags="-s -w -X github.com/pelican-dev/wings/system.Version=${{ steps.vars.outputs.version }}" \
              -o dist/wings_linux_${arch} github.com/pelican-dev/wings
            chmod 755 dist/wings_linux_${arch}
          done

      - name: Extract changelog
        run: |
          sed -n "/^## ${{ steps.vars.outputs.version }}/,/^## /{/^## /b;p}" CHANGELOG.md > ./RELEASE_CHANGELOG

      - name: Create checksums
        run: |
          cd dist
          sha256sum wings_linux_* > ../checksums.txt
          cd ..
          {
            echo -e "\n#### SHA256 Checksums\n\`\`\`"
            cat checksums.txt
            echo -e "\`\`\`\n"
          } >> ./RELEASE_CHANGELOG

      - name: Create release branch
        run: |
          BRANCH=release/${{ steps.vars.outputs.version }}
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b ${BRANCH}
          sed -i "s/var Version = \".*\"/var Version = \"${{ steps.vars.outputs.version }}\"/" system/const.go
          git add system/const.go
          git commit -m "bump version for release"
          git push -u origin ${BRANCH}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          body_path: ./RELEASE_CHANGELOG
          files: |
            dist/wings_linux_amd64
            dist/wings_linux_arm64
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}